const admin = require("firebase-admin");
const { getFirestore } = require("firebase-admin/firestore");
const { trainerProfileUrl } = require("../lib/newsletter-trainer");

if (!admin.apps.length) {
  const raw = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  admin.initializeApp({ credential: raw ? admin.credential.cert(JSON.parse(raw)) : admin.credential.applicationDefault(), storageBucket: process.env.FIREBASE_STORAGE_BUCKET });
}
const db = process.env.FIRESTORE_DATABASE_ID ? getFirestore(admin.app(), process.env.FIRESTORE_DATABASE_ID) : getFirestore(admin.app());
const SITE = (process.env.PUBLIC_SITE_URL || "https://route25.app").replace(/\/$/, "");

function esc(value) { return String(value || "").replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[char]); }
function slug(value) { return String(value || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100); }
function date(value) { const raw = value?.toDate?.() || value; return raw ? new Intl.DateTimeFormat("en-US", { timeZone:"America/Denver", month:"long", day:"numeric", year:"numeric" }).format(new Date(raw)) : ""; }
function socialDetails(url) { try { const parsed = new URL(url), host = parsed.hostname.replace(/^www\./, "").toLowerCase(), path = decodeURIComponent(parsed.pathname).replace(/\/$/, ""); let label = host; if (["x.com","twitter.com"].includes(host)) label = "Twitter (X)"; else if (host.includes("instagram.com")) label = "Instagram"; else if (host.includes("youtube.com") || host === "youtu.be") label = "YouTube"; else if (host.includes("tiktok.com")) label = "TikTok"; else if (host.includes("threads.net")) label = "Threads"; return { label, displayUrl:`${host}${path}` }; } catch { return { label:"Social", displayUrl:"View profile" }; } }
function imageFigure(image, className = "") { return image?.url ? `<figure class="${className}"><button type="button" class="story-image-button" data-story-image="${esc(image.url)}" data-story-alt="${esc(image.alt)}" data-story-caption="${esc(image.caption)}" aria-label="View ${esc(image.alt || "collection photo")} larger"><img src="${esc(image.url)}" alt="${esc(image.alt)}"><span>View larger</span></button>${image.caption ? `<figcaption>${esc(image.caption)}</figcaption>` : ""}</figure>` : ""; }
function products(title, items, linkLabel) { return items.length ? `<div class="collector-group"><h3>${esc(title)}</h3><div class="collector-items">${items.map(item => `<article class="collector-item"><div><strong>${esc(item.name)}</strong>${item.note ? `<small>${esc(item.note)}</small>` : ""}</div>${item.url ? `<a rel="sponsored nofollow" href="${esc(item.url)}">${linkLabel} <span aria-hidden="true">→</span></a>` : ""}</article>`).join("")}</div></div>` : ""; }
function collectionProfile(issue) { const details = [["Favorite",issue.favorite],["Current chase",issue.currentChase],["Ultimate grail",issue.grail]].filter(([,value]) => value); return issue.collectionFocus || details.length ? `<section class="collection-profile"><p class="eyebrow">Collection profile</p>${issue.collectionFocus ? `<p class="collection-focus">${esc(issue.collectionFocus)}</p>` : ""}${details.length ? `<div class="collection-highlights">${details.map(([label,value]) => `<article><small>${label}</small><p>${esc(value)}</p></article>`).join("")}</div>` : ""}</section>` : ""; }
function lightbox() { return `<dialog id="storyLightbox" class="story-lightbox" aria-label="Expanded collection photo"><button type="button" class="lightbox-close" aria-label="Close image">×</button><figure><img alt=""><figcaption></figcaption></figure></dialog><script>(()=>{const dialog=document.querySelector('#storyLightbox');if(!dialog)return;const image=dialog.querySelector('img'),caption=dialog.querySelector('figcaption');document.addEventListener('click',event=>{const trigger=event.target.closest('[data-story-image]');if(!trigger)return;image.src=trigger.dataset.storyImage;image.alt=trigger.dataset.storyAlt||'';caption.textContent=trigger.dataset.storyCaption||'';caption.hidden=!caption.textContent;dialog.showModal()});dialog.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{image.removeAttribute('src')})})()</script>`; }
function pageShell({ title, description, canonical, image, robots = "index,follow", body, schema }) {
  const jsonLd = JSON.stringify(schema || {}).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${esc(robots)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:site_name" content="Route 25"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${image ? `<meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image">` : `<meta name="twitter:card" content="summary">`}<link rel="stylesheet" href="/newsletter/newsletter.css"><script type="application/ld+json">${jsonLd}</script></head><body><header class="newsletter-header"><a class="brand" href="/">Route <span>25</span></a><nav class="newsletter-nav"><a href="/search">Card search</a><a href="/newsletter">Stories</a><a href="/newsletter/submit">Share your collection</a><span class="social-toolbar"><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://x.com/route25app" aria-label="Route 25 on X"><img src="/assets/social-x.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/route25app/" aria-label="Route 25 on Instagram"><img src="/assets/social-instagram.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://discord.gg/WncmGEFuNw" aria-label="Route 25 on Discord"><img src="/assets/social-discord.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://apps.apple.com/us/app/route-25-tcg-social-network/id6755665546" aria-label="Download Route 25 on the App Store"><img src="/assets/social-apple.svg" alt=""></a></span></nav></header>${body}<footer>Some links may be affiliate links. Purchases support Route 25 at no additional cost to you.</footer></body></html>`;
}

module.exports = async (req, res) => {
  const requestedSlug = slug(req.query.slug);
  const snap = requestedSlug ? await db.collection("newsletterIssues").where("slug", "==", requestedSlug).limit(1).get() : null;
  const issue = snap && !snap.empty ? snap.docs[0].data() : null;
  if (!issue || issue.status !== "published" || issue.publicVisibility !== true || issue.isTest === true) {
    res.statusCode = 404;
    res.setHeader("content-type", "text/html; charset=utf-8");
    res.setHeader("cache-control", "no-store");
    return res.end(pageShell({ title:"Story not found — Route 25", description:"This collector story could not be found.", canonical:`${SITE}/newsletter`, robots:"noindex,nofollow", body:'<main id="issue"><h1>Story not found</h1><p class="lede">This collector story is unavailable.</p><a class="button" href="/newsletter">Browse collector stories</a></main>' }));
  }
  const canonical = `${SITE}/newsletter/${issue.slug}`, hero = issue.images?.[0], published = issue.publishedAt || issue.publishAt, trainerUrl = trainerProfileUrl(issue.trainerId, SITE);
  const relatedSnap = await db.collection("newsletterIssues").where("status", "==", "published").limit(10).get();
  const related = relatedSnap.docs.map(doc => doc.data()).filter(item => item.slug !== issue.slug && item.publicVisibility === true && item.isTest !== true).slice(0, 3);
  const relatedHtml = related.length ? `<h2>More collector stories</h2><div class="related-grid">${related.map(item => `<a class="related-card" href="/newsletter/${esc(item.slug)}">${item.images?.[0]?.url ? `<img src="${esc(item.images[0].url)}" alt="">` : ""}<strong>${esc(item.title)}</strong><span>${esc(item.dek || item.summary || "Read the story")}</span></a>`).join("")}</div>` : "<h2>Keep exploring</h2>";
  const trainerCta = trainerUrl ? `<p class="trainer-profile-cta"><a class="button" href="${esc(trainerUrl)}">View this trainer on Route 25</a></p>` : "";
  const social = issue.socialUrl ? socialDetails(issue.socialUrl) : null;
  const body = `<main id="issue"><p class="issue-meta">${issue.issueNumber ? `Issue #${String(Number(issue.issueNumber)).padStart(3,"0")}` : "Collector Story"}${published ? ` · ${esc(date(published))}` : ""}</p><p class="eyebrow">${esc(issue.trainerName || "Collector Story")}</p><h1>${esc(issue.title)}</h1><p class="lede">${esc(issue.dek || issue.summary)}</p>${social ? `<p class="issue-social"><strong>${esc(social.label)}</strong><span aria-hidden="true">→</span><a href="${esc(issue.socialUrl)}" rel="me nofollow">${esc(social.displayUrl)}</a></p>` : ""}${trainerCta}${imageFigure(hero, "issue-hero")}<article class="prose">${issue.bodyHtml || `<p>${esc(issue.summary)}</p>`}</article>${collectionProfile(issue)}${issue.interviewAnswers?.length ? `<section class="interview"><h2>Five questions</h2>${issue.interviewAnswers.map(answer => `<article class="answer"><h3>${esc(answer.question)}</h3><p>${esc(answer.answer)}</p></article>`).join("")}</section>` : ""}${issue.images?.length > 1 ? `<section><h2>Inside the collection</h2><div class="story-gallery">${issue.images.slice(1).map(image => imageFigure(image)).join("")}</div></section>` : ""}${issue.products?.length ? `<section class="collector-corner"><p class="eyebrow">From the collection</p><h2>Collector’s corner</h2><p class="collector-intro">The cards and tools that help shape this collection.</p>${products("Cards mentioned", issue.products.filter(item => item.category === "card"), "View card")}${products("Gear used", issue.products.filter(item => item.category !== "card"), "View gear")}</section>` : ""}<section class="related-stories">${relatedHtml}<a class="button" href="/newsletter">Browse all collector stories</a></section><section class="section"><h2>Get the next collector story</h2><a class="button red" href="/newsletter/subscribe">Subscribe</a></section></main>${lightbox()}`;
  const schema = { "@context":"https://schema.org", "@type":"Article", headline:issue.title, description:issue.dek || issue.summary, image:hero?.url ? [hero.url] : undefined, datePublished:published?.toDate?.()?.toISOString?.() || published, author:{ "@type":"Person", name:issue.trainerName || "Route 25 Collector" }, publisher:{ "@type":"Organization", name:"Route 25", url:SITE }, mainEntityOfPage:canonical };
  res.statusCode = 200;
  res.setHeader("content-type", "text/html; charset=utf-8");
  res.setHeader("cache-control", "s-maxage=300, stale-while-revalidate=3600");
  res.end(pageShell({ title:`${issue.title} — Route 25`, description:issue.dek || issue.summary, canonical, image:hero?.url, body, schema }));
};
