const admin = require("firebase-admin");
const { getFirestore } = require("firebase-admin/firestore");
const { trainerProfileUrl } = require("../lib/newsletter-trainer");
const { socialDetails } = require("../lib/newsletter-social");
const { collectionStoryFields, storyBodyHtml } = require("../lib/newsletter-story");
const { plainTextParagraphs } = require("../lib/newsletter-text");

if (!admin.apps.length) {
  const raw = process.env.FIREBASE_SERVICE_ACCOUNT_JSON;
  admin.initializeApp({ credential: raw ? admin.credential.cert(JSON.parse(raw)) : admin.credential.applicationDefault(), storageBucket: process.env.FIREBASE_STORAGE_BUCKET });
}
const db = process.env.FIRESTORE_DATABASE_ID ? getFirestore(admin.app(), process.env.FIRESTORE_DATABASE_ID) : getFirestore(admin.app());
const SITE = (process.env.PUBLIC_SITE_URL || "https://route25.app").replace(/\/$/, "");

function esc(value) { return String(value || "").replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[char]); }
function textMarkup(value) { return plainTextParagraphs(value).map(paragraph => `<p>${esc(paragraph).replace(/\n/g, "<br>")}</p>`).join(""); }
function slug(value) { return String(value || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100); }
function date(value) { const raw = value?.toDate?.() || value; return raw ? new Intl.DateTimeFormat("en-US", { timeZone:"America/Denver", month:"long", day:"numeric", year:"numeric" }).format(new Date(raw)) : ""; }
function imageFigure(image, className = "", id = "") { return image?.url ? `<figure class="${className}"${id ? ` id="${esc(id)}"` : ""}><button type="button" class="story-image-button" data-story-image="${esc(image.url)}" data-story-alt="${esc(image.alt)}" data-story-caption="${esc(image.caption)}" aria-label="View ${esc(image.alt || "collection photo")} larger"><img src="${esc(image.url)}" alt="${esc(image.alt)}"><span>View larger</span></button>${image.caption ? `<figcaption>${esc(image.caption)}</figcaption>` : ""}</figure>` : ""; }
function products(title, items, linkLabel, linkField, sponsored) { return items.length ? `<div class="collector-group"><h3>${esc(title)}</h3><div class="collector-items">${items.map(item => { const url = item[linkField]; return `<article class="collector-item"><div><strong>${esc(item.name)}</strong>${item.note ? `<small>${esc(item.note)}</small>` : ""}</div>${url ? `<a target="_blank" rel="${sponsored ? "noopener noreferrer sponsored nofollow" : "noopener noreferrer"}" href="${esc(url)}">${linkLabel} <span aria-hidden="true">→</span></a>` : ""}</article>`; }).join("")}</div></div>` : ""; }
function collectionProfile(issue) { const collection = collectionStoryFields(issue), details = [["Favorite",collection.favorite],["Current chase",collection.currentChase],["Ultimate grail",collection.grail]].filter(([,value]) => value); return collection.collectionFocus || details.length ? `<section class="collection-profile"><p class="eyebrow">Collection profile</p>${collection.collectionFocus ? `<div class="collection-focus">${textMarkup(collection.collectionFocus)}</div>` : ""}${details.length ? `<div class="collection-highlights">${details.map(([label,value]) => `<article><small>${label}</small>${textMarkup(value)}</article>`).join("")}</div>` : ""}</section>` : ""; }
function lightbox() { return `<dialog id="storyLightbox" class="story-lightbox" aria-label="Expanded collection photo"><button type="button" class="lightbox-close" aria-label="Close image">×</button><button type="button" class="lightbox-nav lightbox-prev" aria-label="Previous image" hidden>‹</button><button type="button" class="lightbox-nav lightbox-next" aria-label="Next image" hidden>›</button><figure><img alt="" role="button" tabindex="0" aria-label="Zoom in image" aria-pressed="false"><figcaption></figcaption></figure><output class="lightbox-count" aria-live="polite" hidden></output></dialog><script>(()=>{const dialog=document.querySelector('#storyLightbox');if(!dialog)return;const figure=dialog.querySelector('figure'),image=dialog.querySelector('img'),caption=dialog.querySelector('figcaption'),previous=dialog.querySelector('.lightbox-prev'),next=dialog.querySelector('.lightbox-next'),count=dialog.querySelector('.lightbox-count');let index=0;const items=()=>[...document.querySelectorAll('[data-story-image]')],setZoom=zoomed=>{image.classList.toggle('is-zoomed',zoomed);image.setAttribute('aria-pressed',String(zoomed));image.setAttribute('aria-label',zoomed?'Zoom out image':'Zoom in image');if(!zoomed)figure.scrollTo(0,0)},toggleZoom=event=>{const zooming=!image.classList.contains('is-zoomed'),x=event?.offsetX/image.clientWidth||.5,y=event?.offsetY/image.clientHeight||.5;setZoom(zooming);if(zooming)requestAnimationFrame(()=>{figure.scrollLeft=Math.max(0,x*image.clientWidth-figure.clientWidth/2);figure.scrollTop=Math.max(0,y*image.clientHeight-figure.clientHeight/2)})},show=value=>{const available=items();if(!available.length)return;setZoom(false);index=(value+available.length)%available.length;const trigger=available[index],multiple=available.length>1;image.src=trigger.dataset.storyImage;image.alt=trigger.dataset.storyAlt||'';caption.textContent=trigger.dataset.storyCaption||'';caption.hidden=!caption.textContent;previous.hidden=!multiple;next.hidden=!multiple;count.hidden=!multiple;count.textContent=(index+1)+' / '+available.length};document.addEventListener('click',event=>{const trigger=event.target.closest('[data-story-image]');if(!trigger)return;show(items().indexOf(trigger));dialog.showModal()});image.addEventListener('click',toggleZoom);image.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleZoom()}});previous.addEventListener('click',()=>show(index-1));next.addEventListener('click',()=>show(index+1));dialog.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();show(index-1)}if(event.key==='ArrowRight'){event.preventDefault();show(index+1)}});dialog.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{setZoom(false);image.removeAttribute('src')})})()</script>`; }
function pageShell({ title, description, canonical, image, imageAlt = "Route 25 collector spotlight", robots = "index,follow,max-image-preview:large", body, schema }) {
  const jsonLd = JSON.stringify(schema || {}).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${esc(robots)}"><meta name="theme-color" content="#05060a"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="article"><meta property="og:locale" content="en_US"><meta property="og:site_name" content="Route 25"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${image ? `<meta property="og:image" content="${esc(image)}"><meta property="og:image:secure_url" content="${esc(image)}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${esc(imageAlt)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${esc(image)}"><meta name="twitter:image:alt" content="${esc(imageAlt)}">` : `<meta name="twitter:card" content="summary">`}<meta name="twitter:site" content="@route25app"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="stylesheet" href="/newsletter/newsletter.css"><script type="application/ld+json">${jsonLd}</script></head><body><header class="newsletter-header"><a class="brand" href="/">Route <span>25</span></a><nav class="newsletter-nav"><a href="/search">Card search</a><a href="/newsletter">Spotlights</a><a href="/newsletter/submit">Share your collection</a><span class="social-toolbar"><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://x.com/route25app" aria-label="Route 25 on X"><img src="/assets/social-x.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/route25app/" aria-label="Route 25 on Instagram"><img src="/assets/social-instagram.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://discord.gg/WncmGEFuNw" aria-label="Route 25 on Discord"><img src="/assets/social-discord.svg" alt=""></a><a class="social-link" target="_blank" rel="noopener noreferrer" href="https://apps.apple.com/us/app/route-25-tcg-social-network/id6755665546" aria-label="Download Route 25 on the App Store"><img src="/assets/social-apple.svg" alt=""></a></span></nav></header>${body}<footer>Some links may be affiliate links. Purchases support Route 25 at no additional cost to you.</footer></body></html>`;
}

module.exports = async (req, res) => {
  const requestedSlug = slug(req.query.slug);
  const snap = requestedSlug ? await db.collection("newsletterIssues").where("slug", "==", requestedSlug).limit(1).get() : null;
  const issue = snap && !snap.empty ? snap.docs[0].data() : null;
  if (!issue || issue.status !== "published" || issue.publicVisibility !== true || issue.isTest === true) {
    res.statusCode = 404;
    res.setHeader("content-type", "text/html; charset=utf-8");
    res.setHeader("cache-control", "no-store");
    return res.end(pageShell({ title:"Spotlight not found — Route 25", description:"This collector spotlight could not be found.", canonical:`${SITE}/newsletter`, robots:"noindex,nofollow", body:'<main id="issue"><h1>Spotlight not found</h1><p class="lede">This collector spotlight is unavailable.</p><a class="button" href="/newsletter">Browse collector spotlights</a></main>' }));
  }
  const canonical = `${SITE}/newsletter/${issue.slug}`, hero = issue.images?.[0], published = issue.publishedAt || issue.publishAt, trainerUrl = trainerProfileUrl(issue.trainerId, SITE);
  const socialRevision = issue.updatedAt?.toMillis?.() || issue.publishedAt?.toMillis?.() || 0;
  const socialImage = `${SITE}/api/newsletter/og?slug=${encodeURIComponent(issue.slug)}${socialRevision ? `&v=${Math.floor(socialRevision)}` : ""}`;
  const relatedSnap = await db.collection("newsletterIssues").where("status", "==", "published").limit(10).get();
  const related = relatedSnap.docs.map(doc => doc.data()).filter(item => item.slug !== issue.slug && item.publicVisibility === true && item.isTest !== true).slice(0, 3);
  const relatedHtml = related.length ? `<section class="related-stories"><h2>More collector spotlights</h2><div class="related-grid">${related.map(item => `<a class="related-card" href="/newsletter/${esc(item.slug)}">${item.images?.[0]?.url ? `<img src="${esc(item.images[0].url)}" alt="">` : ""}<strong>${esc(item.title)}</strong><span>${esc(item.dek || item.summary || "Read the spotlight")}</span></a>`).join("")}</div></section>` : "";
  const trainerCta = trainerUrl ? `<section class="trainer-app-cta"><p class="eyebrow">Continue in the Route 25 app</p><h2>Find ${esc(issue.trainerName || "this collector")} in the app</h2><p>Visit their Route 25 trainer profile.</p><a class="button" href="${esc(trainerUrl)}">View trainer in the Route 25 app</a></section>` : "";
  const social = issue.socialUrl ? socialDetails(issue.socialUrl) : null;
  const storyBody = storyBodyHtml(issue);
  const body = `<main id="issue"><p class="issue-meta">${issue.issueNumber ? `Issue #${String(Number(issue.issueNumber)).padStart(3,"0")}` : "Collector Spotlight"}${published ? ` · ${esc(date(published))}` : ""}</p><p class="eyebrow">${esc(issue.trainerName || "Collector Spotlight")}</p><h1>${esc(issue.title)}</h1><div class="lede story-summary">${textMarkup(issue.summary)}</div>${social ? `<p class="issue-social"><strong>${esc(social.label)}</strong><span aria-hidden="true">→</span><a target="_blank" href="${esc(issue.socialUrl)}" rel="noopener noreferrer me nofollow">${esc(social.displayUrl)}</a></p>` : ""}${imageFigure(hero, "issue-hero", issue.images?.length > 1 ? "" : "collection-photos")}${storyBody ? `<article class="prose">${storyBody}</article>` : ""}${collectionProfile(issue)}${issue.interviewAnswers?.length ? `<section class="interview"><h2>Five questions</h2>${issue.interviewAnswers.map(answer => `<article class="answer"><h3>${esc(answer.question)}</h3>${textMarkup(answer.answer)}</article>`).join("")}</section>` : ""}${issue.images?.length > 1 ? `<section id="collection-photos"><h2>Inside the collection</h2><div class="story-gallery">${issue.images.slice(1).map(image => imageFigure(image)).join("")}</div></section>` : ""}${issue.products?.length ? `<section class="collector-corner"><p class="eyebrow">From the collection</p><h2>Collector’s corner</h2><p class="collector-intro">The cards and tools that help shape this collection.</p>${products("Cards mentioned", issue.products.filter(item => item.category === "card"), "View card", "route25Url", false)}${products("Gear used", issue.products.filter(item => item.category !== "card"), "Shop gear", "url", true)}</section>` : ""}${trainerCta}${relatedHtml}<section class="section subscribe-prompt"><h2>Get the next collector spotlight</h2><p>Delivered to your inbox every Saturday</p><div class="subscribe-actions"><a class="button red" href="/newsletter/subscribe">Subscribe</a><a class="browse-spotlights-link" href="/newsletter">Browse all collector spotlights <span aria-hidden="true">→</span></a></div></section></main>${lightbox()}`;
  const schema = { "@context":"https://schema.org", "@type":"Article", headline:issue.title, description:issue.dek || issue.summary, image:hero?.url ? [hero.url] : undefined, datePublished:published?.toDate?.()?.toISOString?.() || published, author:{ "@type":"Person", name:issue.trainerName || "Route 25 Collector" }, publisher:{ "@type":"Organization", name:"Route 25", url:SITE }, mainEntityOfPage:canonical };
  res.statusCode = 200;
  res.setHeader("content-type", "text/html; charset=utf-8");
  res.setHeader("cache-control", "s-maxage=300, stale-while-revalidate=3600");
  res.end(pageShell({ title:`${issue.title} — Route 25`, description:issue.dek || issue.summary, canonical, image:socialImage, imageAlt:`${issue.title} — ${issue.trainerName || "Route 25 collector spotlight"}`, body, schema }));
};
